swagger: '2.0'
info:
  title: Cloud Run YAML
  description: Cloud Run YAML
  version: 0.0.1
host: softcon-exercises-hv56hizgwq-uc.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://softcon-exercises-hv56hizgwq-uc.a.run.app
# securityDefinitions:
#   softcon-security:
#     authorizationUrl: ""
#     flow: "implicit"
#     type: "oauth2"
#     x-google-issuer: "softcon-exercises-1@softcon-exercises.iam.gserviceaccount.com"
#     x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/softcon-exercises-1@softcon-exercises.iam.gserviceaccount.com"
paths:
  /random:
    get:
      summary: Gives out a random number from 1 - 3
      operationId: random
      # parameters:
      # - name: authorization
      #   in: header
      #   type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  random:
                    type: number
              success:
                type: boolean
